name: Update Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get latest WSA version (GitHub Releases)
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository	 }}
          releases-only: true
        id: latesttag
      - name: Get latest WSA version (Microsoft Store)
        run: |
          echo "wsaver=$(python get_latest_wsa_version.py 'x64' 'RP')" >> $GITHUB_ENV
      - name: Should build?
        id: should_build
        shell: bash
        run: |
          GHVER=$(echo ${{ steps.latesttag.outputs.tag }} | cut -c 5-)
          echo "Microsoft Store Version: ${{ env.wsaver }}"
          echo "GitHub Releases Version: $GHVER"
          if $(dpkg --compare-versions "$GHVER" "lt" "${{ env.wsaver }}"); then
            echo "Newer version is available. Building it."
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
          else
            echo "Skipping build. Same (or newer) build available on GitHub Releases."
            echo "SHOULD_BUILD=0" >> $GITHUB_OUTPUT
          fi
    outputs:
      SHOULD_BUILD: ${{ steps.should_build.outputs.SHOULD_BUILD }}

  build_x64:
    permissions: write-all
    needs: check
    uses: ./.github/workflows/wsa.yml
    if: ${{ needs.check.outputs.SHOULD_BUILD == 1 }}
    secrets: inherit
    with:
      arch: 'x64'
      release_type: 'Release Preview'
      gapps_brand: 'MindTheGapps'
      root_ver: 'Magisk (Stable)'
      remove_amazon: true
  build_arm64:
    permissions: write-all
    needs: check
    uses: ./.github/workflows/wsa.yml
    if: ${{ needs.check.outputs.SHOULD_BUILD == 1 }}
    secrets: inherit
    with:
      arch: 'ARM64'
      release_type: 'Release Preview'
      gapps_brand: 'MindTheGapps'
      root_ver: 'Magisk (Stable)'
      remove_amazon: true
